version: '3'
services:
  androidapi:
    build: 
      context: .
      dockerfile: ./Services/AndroidApi/dockerfile
    ports:
      - "8080:8080"
    environment:
      CATALOGUS_ADDRESS: "http://catalog"
      CATALOGUS_PORT: "8080"
    networks:
      - my-network
    depends_on:
      - otel-collector

  catalog:
    build: 
      context: .
      dockerfile: ./Services/Catalog/dockerfile
    ports:
      - "8081:8080"
    networks:
      - my-network
    depends_on:
      - otel-collector
      - mysql
    restart: on-failure

  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    platform: linux/arm64
    networks:
      - my-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.78.0
    volumes:
      - ./otel/otel-config.yaml:/etc/otel/config.yaml
      - ./log:/log/otel
    command: --config /etc/otel/config.yaml
    environment:
      JAEGER_ENDPOINT: "jaeger:4317"
      LOKI_ENDPOINT: "http://loki:3100/loki/api/v1/push"
    ports:
      - "8889:8889"   # Prometheus metrics exporter (scrape endpoint)
      - "13133:13133" # health_check extension
      - "55679:55679" # ZPages extension
    depends_on:
      - jaeger
      - prometheus
      - loki
    platform: linux/arm64
    networks:
      - my-network

  jaeger:
    image: jaegertracing/all-in-one:1.46.0
    ports:
      - "16686:16686" # Jaeger Web UI
    platform: linux/arm64
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:v2.42.0
    volumes:
      - ./otel/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    platform: linux/arm64
    networks:
      - my-network

  loki:
    image: grafana/loki:2.7.4
    ports:
      - "3100:3100"
    platform: linux/arm64/v8
    networks:
      - my-network

  grafana:
    image: grafana/grafana:9.4.3
    volumes:
      - ./otel/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    ports:
      - "3000:3000"
    platform: linux/arm64/v8
    networks:
      - my-network

networks:
  my-network:
