{
 "title": "Logs",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Average Response Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_sum{exported_job=\"AndroidApi\"}[$__rate_interval])) / sum(rate(http_server_duration_milliseconds_count{exported_job=\"AndroidApi\"}[$__rate_interval]))",
     "legendFormat": "AndroidApi"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{exported_job=\"AndroidApi\"}[$__rate_interval]))",
     "legendFormat": "AndroidApi"
    }
   ]
  },
  {
   "title": "Request Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{exported_job=\"AndroidApi\", http_status_code=\"500\"}[$__rate_interval]))",
     "legendFormat": "AndroidApi"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"AndroidApi\"}[$__rate_interval])))",
     "legendFormat": "AndroidApi"
    }
   ]
  }
 ]
}