FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /App

# Copy everything
COPY ./Services/AndroidApi ./Services/AndroidApi/

WORKDIR /App/Services/AndroidApi

# Restore as distinct layers
RUN dotnet restore

RUN dotnet test

# Build and publish a release
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0

RUN apt-get update && apt-get install -y curl

# Install OpenTelemetry .NET Automatic Instrumentation
ARG OTEL_VERSION=1.0.0
ADD https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/download/v${OTEL_VERSION}/otel-dotnet-auto-install.sh otel-dotnet-auto-install.sh
RUN apt-get update && apt-get install -y unzip && \
    OTEL_DOTNET_AUTO_HOME="/otel-dotnet-auto" sh otel-dotnet-auto-install.sh

ENV ASPNETCORE_URLS=http://+:8080

WORKDIR /App
COPY --from=build-env /App/Services/AndroidApi/out .
ENTRYPOINT ["dotnet", "AndroidApi.dll"]
